### ISSUE TITLE
Share resources 

### ISSUE THREAD

**Issue by YosefJoo** [anas-elgarhy/Ayah-intellij#1]
Can you share all resource that help you create plugin ❤️

**Comment by anas-elgarhy** [comment]
ok :D

**Comment by anas-elgarhy** [comment]
- https://github.com/JetBrains/intellij-sdk-code-samples
- https://plugins.jetbrains.com/docs/intellij/notifications.html#top-level-notifications-balloons
- https://plugins.jetbrains.com/docs/intellij/deployment.html
- https://github.com/halirutan/IntelliJ-Key-Promoter-X

**Comment by YosefJoo** [comment]
شكرا جدا 
ويارب افهم😅😅❤️

**Comment by anas-elgarhy** [comment]
https://plugins.jetbrains.com/intellij-platform-explorer/extensions

**Comment by anas-elgarhy** [comment]
https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html
